### ISSUE TITLE
Right Click with Bluetooth Mouse

### ISSUE THREAD

**Issue by Alvyssy** [lowtraxx/TSVNC#1]
I'm using this app as it works well and has alt gr support, however when I right click with my mouse it always clicks on the top left corner, whereas apps such as bvnc has proper mouse support but no alt gr function

**Comment by lowtraxx** [comment]
Which Device and Mouse are you using? I just tried it on a Tab S6 with a Razer Basilisk X Bluetooth Mouse and there I am able to Right Click normally anywhere.

**Comment by Alvyssy** [comment]
I am using BM30X bluetooth mouse

Il giorno mar 6 ott 2020 alle ore 23:58 lowtraxx <notifications@github.com>
ha scritto:

**Comment by rdhiviyan** [comment]
got same issue with usb mouse on my realme 1

**Comment by lowtraxx** [comment]
@rdhiviyan and @Alvyssy could you try the latest version again (0.7.3 in PlayStore or compiled from latest git) and see if it is fixed for you

**Comment by Alvyssy** [comment]
Hi thank you for your support but it still doesn't work

Il Mer 9 Dic 2020, 9:55 PM lowtraxx <notifications@github.com> ha scritto:

**Comment by kbarni** [comment]
Affects me too (TSVNC 0.7.5 from Play Store). Right click always on the top-right corner, no matter where the mouse pointer is.
Tried on a Samsung Galaxy S8; VNC to a locally installed Linux (using Andronix). 
It's present in normal and Dex mode. I tried with a USB mouse, and also connected to a Windows desktop (Dex to Desktop) - same result.
Other VNC clients are handling right-click well (tested on bVNC and MultiVNC)

**Comment by lowtraxx** [comment]
I got myself a cheap S8+ and will try to reproduce there. Will keep you posted on fixes/workarounds.

**Comment by lowtraxx** [comment]
Fixed in master.

**Comment by Alvyssy** [comment]
Thank you, your app has come a long way

Il Ven 22 Gen 2021, 2:35 PM lowtraxx <notifications@github.com> ha scritto:
