### ISSUE TITLE
Scrolling is interpreted as touch input

### ISSUE THREAD

**Issue by jonas-w** [lowtraxx/TSVNC#2]
I love this VNC Viewer because it has alt gr support. But when I use my mouse wheel to scroll, it gets interpreted as normal touch input. I'm currently using the Tab S7+ with the Samsung Keyboard cover. In other VNC clients scrolling works BUT they all don't have alt gr support....

**Comment by jonas-w** [comment]
Ich hab mir grade die Version vom Google Playstore heruntergeladen und das Problem ist exakt dasselbe.

Hab dann auch von den Sources Compiled, aber war exakt dasselbe Problem, wie ich es oben beschrieben hatte :/

Aber vielen Dank für die Antwort.

**Comment by lowtraxx** [comment]
Sadly I am not able to reproduce this here. For me it works now. Tested with a BT mouse, a wired mouse and two RF mice. I will reopen the ticket and try to reproduce anyway.

**Comment by lowtraxx** [comment]
Scrolling now also fixed for Touchpads. New version 0.7.3.
